### PR TITLE
compile scss file for the vueify(browserify)

### PR DESCRIPTION
**Pull request by Alideniz**

### CODE REVIEW

**Comment by AbdullahG** [comment]
@fritx I am waiting the pr

**Comment by fritx** [comment]
@AbdullahG hold on, just found your branch has problem rendering in my Chrome.

**Comment by fritx** [comment]
@AbdullahG seems we should pack the library using rollup instead of webpack?

**Comment by fritx** [comment]
I've found that UglifyJS is needed to use it in vueify(browserify).
(Tested under https://github.com/vuejs-templates/browserify.)

The error below while dev was due to a webpack script not being removed while it is in a `if (false) {}`.

```plain
Error: Cannot find module '!!../node_modules/css-loader/index.js!../node_modules/vue-loader/lib/style-rewriter.js?id=data-v-05ccc8af!../node_modules/sass-loader/index.js!./At.scss' from '/xxx/node_modules/vue-at/dist'
```

**Comment by fritx** [comment]
@Alideniz @AbdullahG try 2.3.2 with vueify, thanks!

**Pull request merged**
