### PR TITLE
Library update

### PR DESCRIPTION
**Pull request by nsano-rururu**
**update**

- babel 6 to 7
- cross-env 3.0.0 to 7.0.3
- css-loader 0.25.0 to 0.28.11
- element-ui 2.8.2 to 2.15.6
- file-loader 0.9.0 to 1.1.9
- node-sass 4.12.0 to 7.0.0
- sass-loader 4.1.0 to 6.0.6
- textarea-caret 3.0.2 to 3.1.0
- url-loader 1.1.2 to 4.1.1
- vue 2.6.10 to 2.6.14
- vue-style-loader 1.0.0 to 4.1.3
- vue-template-compiler 2.6.10 to 2.6.14
- vuetify 1.5.13 to 2.6.1
- webpack 2.1.0-beta.25 to 3.12.0

**remove**

- （deprecated）uglifyjs-webpack-plugin 
  
**add**

- babel-preset-minify

---

I'm not very familiar with webpack, so there may be missing fixes.

### CODE REVIEW

**Comment by nsano-rururu** [comment]
Switching project build to vue-cli 4 may come first

**Comment by fritx** [comment]
@nsano-rururu merged already! Thanks, but I think most of the babel plugins included are unnecessary

**Comment by fritx** [comment]
@nsano-rururu I have a bad news here, these days I found that the [vue2](https://github.com/fritx/vue-at/tree/vue2) branch has some problem. (vue3 branch is okay)

I get `Error: Can't find intersection` in terminal each time I modify `src/At.vue`

If I tried to revert recent merged PRs, it will work again -- https://github.com/fritx/vue-at/commits/try-to-fix-webpack-reload

Seems this #138 PR introduced the problem I meet, do you have the same problem?

**Comment by nsano-rururu** [comment]
@fritx 

I didn't notice the problem because I wasn't using the [OSS](https://github.com/johnsusek/praeco) I maintain with the version that pulled in 138 pull requests. Since I was using 2.5.0-beta.2. . .

**Comment by fritx** [comment]
@nsano-rururu never mind. The users won't be affected.
It's just a local developing issue I've recently met.
I'm not sure if you guys are also coming across it.

**Comment by fritx** [comment]
> I get Error: Can't find intersection (probably https://github.com/babel/minify/issues/904) in terminal each time I modify src/At.vue

The error looks like:

image

**Pull request merged**
