### PR TITLE
add selection using tab

### LINKED ISSUE #60: Allow selections using Tab
It looks like At.js allows selecting values using the tab key along with the enter key. It would be nice if vue-at also had this functionality.

### PR DESCRIPTION
**Pull request by MaciejKus**
resolves #60

### CODE REVIEW

**Comment by fritx** [comment]
Good PR, merged to #59  no problem

**Comment by MaciejKus** [comment]
Hi @fritx ,

Sorry for the duplicate pull request. 

That is interesting that in Asia the Tab key is not used in the same way as in North America.  I have updated this pull request to make the Tab a prop option.

**Comment by fritx** [comment]
Cool, but there is conflicts in this PR, would resolve it later.

Btw, looks the git committer was not bound to your github account, would be great to have you in [contributors](https://github.com/fritx/vue-at/graphs/contributors).

**Comment by fritx** [comment]
Sorry for the delay, would get into it soon. @MaciejKus

**Comment by Doogal666** [comment]
Is this in 2.5.0-beta.2? I'm still not able to use the tab key, do I need to enable it?

**Comment by Doogal666** [comment]
Ignore me, :tabSelect="true" enables it

**Pull request merged**
